const actions = {
    JOIN_USER: 'JOIN_USER',
    JOIN_USER_VALID: 'JOIN_USER_VALID',
    LOGIN_USER: 'LOGIN_USER',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_ERROR: 'LOGOUT_ERROR',
    LOGIN_KAKAO_TOKEN: 'LOGIN_KAKAO_TOKEN',
    LOGIN_KAKAO_USER: 'LOGIN_KAKAO_USER',
    
};

export default actions;